name: Build rk3399-edk2

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REPO_URL: https://github.com/shantur/rk3399-edk2
  REPO_BRANCH: master
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get update
        sudo -E apt-get install build-essential acpica-tools nasm uuid-dev gcc-aarch64-linux-gnu
        sudo timedatectl set-timezone "$TZ"
        export WORKSPACE=/workspace
        sudo mkdir -p /workspace
        cd /workspace
        sudo chown $USER:$GROUPS /workspace

    - name: Clone source code
      working-directory: /workspace
      run: |
        git clone https://github.com/tianocore/edk2.git
        pushd edk2
        git checkout 46f4c9677c615d862649459392f8f55b3e6567c2
        popd
        git clone https://github.com/tianocore/edk2-non-osi.git
        pushd edk2-non-osi
        git checkout 1e2ca640be54d7a4d5d804c4f33894d099432de3
        popd
        git clone https://github.com/tianocore/edk2-platforms.git
        pushd edk2-platforms
        git checkout 861c200cda1417539d46fe3b1eba2b582fa72cbb
        popd
        git clone https://github.com/shantur/rk3399-edk2.git edk2-platforms/Platform/Rockchip

    - name: Compile the EDK2
      id: compile
      run: |
        export WORKSPACE=/workspace
        export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
        export PACKAGES_PATH=$WORKSPACE/edk2:$WORKSPACE/edk2-platforms:$WORKSPACE/edk2-non-osi
        export CFLAGS="-Wno-error"
        export CXXFLAGS="-Wno-error"
        cd /workspace
        . edk2/edksetup.sh
        make -C edk2/BaseTools
        build -a AARCH64 -t GCC5 -p edk2-platforms/Platform/Rockchip/Rk3399Pkg/Rk3399-SDK.dsc -b DEBUG
        edk2-platforms/Platform/Rockchip/Rk3399Pkg/Tools/loaderimage --pack --uboot Build/Rk3399-SDK/DEBUG_GCC5/FV/RK3399_SDK_UEFI.fd RK3399_SDK_UEFI.img
        mkdir /workspace/uefi_output
    
    - name: SSH connection to Actions
      uses: csexton/debugger-action@master
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
      
    - name: Copy files
      run: |
        ls
        pwd
        ls *
        cp /workspace/RK3399_SDK_UEFI.img /workspace/uefi_output
        cp /workspace/Build/Rk3399-SDK/DEBUG_GCC5/FV/RK3399_SDK_UEFI.fd /workspace/uefi_output
        cp Rk3399Pkg/Tools/Bin/idbloader.img /workspace/uefi_output/idbloader.img 
        cp Rk3399Pkg/Tools/Bin/trust.img /workspace/uefi_output/trust.img

    - name: Create disk image
      run: |
        # 変数の定義
        IMAGE="/workspace/uefi_output/disk.img"
        SIZE="128M"
        SECTOR_SIZE=512

        # イメージファイルの作成
        dd if=/dev/zero of=$IMAGE bs=$SIZE count=1

        # パーティションテーブルの作成
        parted $IMAGE --script mklabel gpt

        # パーティションの作成
        parted $IMAGE --script mkpart primary 64s 8063s
        parted $IMAGE --script name 1 loader1
        parted $IMAGE --script mkpart primary 8064s 8191s
        parted $IMAGE --script name 2 reserved1
        parted $IMAGE --script mkpart primary 8192s 16383s
        parted $IMAGE --script name 3 reserved2
        parted $IMAGE --script mkpart primary 16384s 24575s
        parted $IMAGE --script name 4 loader2
        parted $IMAGE --script mkpart primary 24576s 32767s
        parted $IMAGE --script name 5 atf
        parted $IMAGE --script mkpart ESP 32768s 262143s
        parted $IMAGE --script name 6 efi_esp
        parted $IMAGE --script set 6 boot on

        # ファイルの書き込み
        # loader1
        dd if=/workspace/uefi_output/idbloader.img of=$IMAGE bs=$SECTOR_SIZE seek=64 conv=notrunc

        # loader2
        dd if=/workspace/uefi_output/RK3399_SDK_UEFI.img of=$IMAGE bs=$SECTOR_SIZE seek=16384 conv=notrunc

        # atf
        dd if=/workspace/uefi_output/trust.img of=$IMAGE bs=$SECTOR_SIZE seek=24576 conv=notrunc

        # efi espのフォーマット
        LOOP_DEV=$(losetup -fP --show $IMAGE)
        mkfs.vfat ${LOOP_DEV}p6
        losetup -d $LOOP_DEV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: env.UPLOAD_BIN_DIR == 'true'
      with:
        name: efi_target
        path: /workspace/uefi_output

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd /workspace/uefi_output
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: uefi_firmware
        path: ${{ env.FIRMWARE }}
